MVCCrudWithoutEF/Models/BookViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace MVCCrudWithoutEF.Models
{
    public class BookViewModel
    {
        [Key]
        public int BookID { get; set; }

        [Required]
        public string Title { get; set; }

        [Required]
        public string Author { get; set; }

        [Range(1, int.MaxValue, ErrorMessage = "Should be greater or equal to 1")]
        public int Price { get; set; }
    }
}

MVCCrudWithoutEF/Models/ErrorViewModel.cs
using System;

namespace MVCCrudWithoutEF.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MVCCrudWithoutEF/Controllers/BookApiController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MVCCrudWithoutEF.Interfaces;
using MVCCrudWithoutEF.Models;

namespace MVCCrudWithoutEF.Controllers
{
    public class BookApiController : Controller
    {
        private readonly IBooks _ibooks;

        public BookApiController(IBooks bookList)
        {
            this._ibooks = bookList;
        }

        [HttpGet, ActionName("GetBook")]
        public IActionResult GetBook()
        {
            var result = _ibooks.BookList();
            return Json(new { status = 200, data = result });
        }

        [HttpPost, ActionName("SubmitBook")]
        public IActionResult SubmitBook([FromBody] BookViewModel requestBody)
        {
            var addBook = _ibooks.AddBook(requestBody);

            if(addBook)
            {
                return Json(new { status = 200, message = "Success" });
            }
            else
            {
                return Json(new { status = 500, message = "Failed" });
            }
        }

        [HttpGet, ActionName("GetEditBook")]
        public IActionResult GetEditBook(int id)
        {
            var result = _ibooks.GetEditBook(id);

                return Json(new { status = 200, data = result }); 
        }

        [HttpPut, ActionName("UpdateBook")]
        public IActionResult UpdateBook(int id,[FromBody] BookViewModel requestBody)
        {
            var updateBook = _ibooks.EditBook(id, requestBody);

            if(updateBook)
            {
                return Json(new { status = 200, message = "Succesfully updated" });
            }
            else
            {
                return Json(new { status = 500, message = "Error" });
            }
        }

        [HttpDelete, ActionName("DeleteBook")]
        public IActionResult DeleteBook(int id)
        {
            var deleteBook = _ibooks.DeleteBook(id);

            if(deleteBook)
            {
                return Json(new { status = 200, message = "Book Deleted" });
            }
            else
            {
                return Json(new { status = 500, message = "Error" });
            }
        }
    }
}

MVCCrudWithoutEF/Controllers/BookController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Data;
using System.Data.SqlClient;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MVCCrudWithoutEF.Models;
using Microsoft.Extensions.Configuration;
using MVCCrudWithoutEF.Interfaces;

namespace MVCCrudWithoutEF.Controllers
{
    public class BookController : Controller
    {
        private readonly IConfiguration _configuration;
        private readonly IBooks _ibooks;

        public BookController(IConfiguration configuration, IBooks bookList)
        {
            this._configuration = configuration;
            this._ibooks = bookList;
        }

        // GET: Book
        public ActionResult Index()
        {
            var BookList = _ibooks.BookList();
            
            return View(BookList);
        }

        // GET: Book/Add/
        public ActionResult Add(int id)
        {
            BookViewModel bookViewModel = new BookViewModel();
            return View(bookViewModel);
        }

        // POST: Book/Add/
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Add(BookViewModel book)
        {
            if (ModelState.IsValid)
            {
                var AddBook = _ibooks.AddBook(book);
                return RedirectToAction(nameof(Index));
            }
            return View();
        }

        // GET: Book/Edit/5
        public ActionResult Edit(int id)
        {

            //ViewBag.Data = Book;

            ViewBag.Data = _ibooks.GetEditBook(id);
            return View(_ibooks.GetEditBook(id));
        }

        // POST: Book/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, BookViewModel book)
        {
            if (ModelState.IsValid)
            {
                var editBook = _ibooks.EditBook(id, book);
                return RedirectToAction(nameof(Index));
            }
            return View();
        }

        // GET: Book/Delete/5
        [HttpGet]
        public ActionResult Delete(int id)
        {
            ViewBag.Data = _ibooks.GetDeleteBook(id);
            return View(_ibooks.GetDeleteBook(id));
        } 

        // POST: Book/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteBook(int id)
        {
            var deleteBook = _ibooks.DeleteBook(id);
            Console.WriteLine(deleteBook);
            return RedirectToAction(nameof(Index));
        }
    }
}

MVCCrudWithoutEF/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MVCCrudWithoutEF.Models;

namespace MVCCrudWithoutEF.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MVCCrudWithoutEF/Views/Book/Add.cshtml
@model MVCCrudWithoutEF.Models.BookViewModel

@{
    ViewData["Title"] = "Add Book";
}

<h1>@ViewData["Title"]</h1>


<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Add">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="BookID" />
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Author" class="control-label"></label>
                <input asp-for="Author" class="form-control" />
                <span asp-validation-for="Author" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Add" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MVCCrudWithoutEF/Views/Book/Delete.cshtml
@model MVCCrudWithoutEF.Models.BookViewModel

@{
    ViewData["Title"] = "Delete";
    var bookDelete = ViewBag.Data;
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Movie</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            <p><strong>Title</strong></p> 
        </dt>
        <dd class="col-sm-10">
            <p>@bookDelete.Title</p>
        </dd>
        <dt class="col-sm-2">
            <p><strong>Author</strong></p>
        </dt>
        <dd class="col-sm-10">
            <p>@bookDelete.Author</p>
        </dd>
        <dt class="col-sm-2">
            <p><strong>Price</strong></p>
        </dt>
        <dd class="col-sm-10">
            <p>@bookDelete.Price</p>
        </dd>
    </dl>

    <form asp-action="DeleteBook" asp-route-id="@bookDelete.BookID">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

MVCCrudWithoutEF/Views/Book/Edit.cshtml
@model MVCCrudWithoutEF.Models.BookViewModel

@{
    ViewData["Title"] = "Edit";
    var bookEdit = ViewBag.Data;
}

<h1>@ViewData["Title"]</h1>

<h4>Movie</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="BookID" />
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" value="@bookEdit.Title" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Author" class="control-label"></label>
                <input asp-for="Author" class="form-control" value="@bookEdit.Author" />
                <span asp-validation-for="Author" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" value="@bookEdit.Price" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MVCCrudWithoutEF/Views/Book/Index.cshtml
@model IEnumerable<MVCCrudWithoutEF.Models.BookViewModel>

@{
    ViewData["Title"] = "List of Books";
}

<h1>@ViewData["Title"]</h1>

<p>
    <a asp-action="Add">Create New</a>
</p>
<form asp-controller="Movies" asp-action="Index" method="get">
</form>
<table class="table table-bordered">
    <thead>
        <tr>
            <th>Books Title</th>
            <th>Author</th>
            <th>Price</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach(var book in Model)
            {
                <tr>
                    <td>
                        @book.Title
                    </td>
                    <td>
                        @book.Author
                    </td>
                    <td>
                        @book.Price
                    </td>
                    <td>
                        <a asp-action="Edit"  asp-route-id="@book.BookID">Edit</a> | 
                        <a asp-action="Delete" asp-route-id="@book.BookID">Delete</a>
                    </td>
                </tr>
            }
    </tbody>
</table>

MVCCrudWithoutEF/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MVCCrudWithoutEF/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVCCrudWithoutEF</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Book" asp-action="Index">Books List</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - MVCCrudWithoutEF - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>